#!/usr/bin/env python3

import configparser
import argparse
import os

SYSFS_DIR="/sys/module/hid_fanatec/drivers/hid:fanatec/"

def find_sysfs() -> str:
    counter=0
    for(root,dirs,files) in os.walk(SYSFS_DIR, followlinks=True):
        counter += 1

        # arbitrary max counter value to avoid loops
        if counter > 100:
            raise Exception(f'sysfs not found (counter={counter})')

        if "ftec_tuning" in dirs:
            ftec_tuning_dir=os.path.join(root, "ftec_tuning")
            device_id=os.path.basename(os.path.dirname(ftec_tuning_dir))
            return os.path.join(ftec_tuning_dir,device_id)

    raise Exception('sysfs not found')

def applyConfiguration(filename: str, profile: str, output: str):
    parser = configparser.RawConfigParser()
    parser.optionxform = str
    parser.read(filename)

    for name, value in parser.items(profile):
        fpath = os.path.join(output, name)
        with open(fpath, "w") as f:
            f.write(value)

def main():
    parser = argparse.ArgumentParser()
    # parser.add_argument('filename')
    parser.add_argument('filename', nargs='?', const=1, type=str, default="profiles.ini")
    parser.add_argument('profile')
    parser.add_argument('output', nargs='?', const=1, type=str, default=find_sysfs())
    args = parser.parse_args()
    applyConfiguration(args.filename, args.profile, args.output)
    applyConfiguration(args.filename, "all", args.output)


if __name__ == "__main__":
    main()
