#!/usr/bin/env python3

import configparser
import argparse
import logging
import os
import sys

SYSFS_PATH="/sys/module/hid_fanatec/drivers/hid:fanatec/"
PROFILE_FILE="profiles.ini"

# Custom ConfigParser to preserve case
class CaseSensitiveConfigParser(configparser.ConfigParser):
    def optionxform(self, optionstr):
        return optionstr # Return the option name as is, preserving case

# recursive file search
def search_filepath(top: str, filename: str, max_depth: int = 3) -> str:
    if not os.path.isdir(top):
        raise Exception(f'topdir {top} not found')

    for(root,dirs,files) in os.walk(top, followlinks=True):
        current_depth = root.count(os.sep) - top.count(os.sep)

        # max depth to avoid loops
        if current_depth > max_depth:
            del dirs[:]

        if filename in files:
            return root

    raise Exception(f'{filename} not found')


# Configure driver
def applyConfiguration(profile_name: str, output: str):
    current_script_path = os.path.abspath(__file__)
    script_directory = os.path.dirname(current_script_path)
    profiles_ini_path = os.path.join(script_directory, PROFILE_FILE)

    if not os.path.isfile(profiles_ini_path):
        raise Exception(f'file {PROFILE_FILE} does not exist')

    config = CaseSensitiveConfigParser()
    config.read(profiles_ini_path)
    if config.has_section(profile_name):
        profile_values = {key: value for key, value in config.items(profile_name)}

        for name, value in profile_values.items():
            fpath = os.path.join(output, name)
            # if parameter not found just skip it
            if not os.path.isfile(fpath):
                logging.debug(f'{name} does not exist (skipped)')
            else:
                with open(fpath, "w") as f:
                    f.write(str(value))
                logging.debug(f'{name} set to {value}')
    else:
        logging.error(f'Profile {profile_name} not found in configuration.')


# main function
def main():
    logging.basicConfig(format='%(levelname)s: %(message)s', level=logging.DEBUG)

    parser = argparse.ArgumentParser()
    parser.add_argument('profile', type=str)
    parser.add_argument('-s', '--sysfs_dir', nargs='?', const=1, type=str, default=SYSFS_PATH)
    args = parser.parse_args()

    try:
        output = search_filepath( args.sysfs_dir, 'advanced_mode' )
        logging.debug(f'path={output}')
        logging.info(f'device id    {os.path.basename(output)}')

        device_input = search_filepath( args.sysfs_dir, 'name' )
        with open( os.path.join(device_input, 'name'), "r" ) as f:
            device_name = f.read()
            logging.info(f'device       {device_name.strip()}')

        applyConfiguration(args.profile, output)
        sys.exit(0)

    except Exception as e:
        logging.error(e)
        sys.exit(1)

if __name__ == "__main__":
    main()
